---
title: "Midterm Markdown"
author: "Christina Mitchell"
date: "2024-03-18"
output: html_document
html_document:
    toc: true
    toc_float: true
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(sf)
library(spdep)
library(caret)
library(ckanr)
library(FNN)
library(grid)
library(gridExtra)
library(ggcorrplot) 
library(corrr)      
library(kableExtra)
library(jtools)     
library(ggstance) 
library(ggpubr)    
library(broom.mixed) 
library(RColorBrewer)
library(stargazer)
library(geojsonsf)
library(nngeo)
library(FNN)

source("https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/functions.r")
```

## Property Value Prediction in King County, Washington 

This predictive model seeks to... 

Data for this project was gathered by... 

# Loading in Data

```{r load_variables, cache = TRUE}

csv_url <- "https://raw.githubusercontent.com/cnmitch01/PPA-Midterm/main/data/kc_house_data.csv"

parks_url <- "https://raw.githubusercontent.com/cnmitch01/PPA-Midterm/main/data/park_facilities.csv"

graduation_url <- "https://raw.githubusercontent.com/cnmitch01/PPA-Midterm/main/data/kc_graduation_rates_2014-2015.csv"

kc_house_data <- read_csv(csv_url) 

kc_parks_data <- st_read(parks_url)

kc_graduation_data <- st_read(graduation_url)

```
## Gathering Outside Data - Data Wrangling 

```{r data_wrangling, cache = TRUE}
#Making the data spatial 
kc_house_sf <- st_as_sf(kc_house_data, coords = c("long", "lat"), crs = "EPSG:4326")

kc_parks_sf <- st_as_sf(kc_parks_data, coords = c("X", "Y"), crs = "EPSG:4326")

#Organizing parks data to incorporate as variable for model 
kc_parks_sf <- kc_parks_sf %>%
            filter(SiteType == "Park Site")

kc_variables_sf <-
  kc_house_sf %>% 
    mutate(
      parks_nn1 = nn_function(st_coordinates(kc_house_sf), 
                              st_coordinates(kc_parks_sf), k = 1))

#Bringing in schools data 

## First - graduation rates by district 
kc_graduation_data <- kc_graduation_data %>%
  filter(County == "King" & StudentGroupType == "All"& Cohort == "Four Year") %>% #four-year graduation rate for all students in KC
  select(DistrictCode, DistrictName, SchoolCode, SchoolName, GraduationRate) %>%
  mutate(GraduationRate = as.numeric(GraduationRate)) %>%
  drop_na(GraduationRate)

```


## Summary Statistics - Understanding the Data 

```{r summary_stats, cache = TRUE}

lm.fit <- lm(price ~ bedrooms + sqft_living + floors + yr_built, data = kc_house_data) 
summary(lm.fit)
#seems like there is a negative relationship between housing age & price, but that could be because of certain ages

kc_house_data$yr_built_category <- cut(kc_house_data$yr_built, 
                                        breaks = c(1900, 1940, 1961, 1980, 2000, 2016),
                                        labels = c(1, 2, 3, 4, 5),
                                        include.lowest = TRUE)

lm.fit1 <- lm(price ~ bedrooms + sqft_living + floors + yr_built_category, data = kc_house_data)
summary(lm.fit1)
#hmmm lets try something else 

lm.fit2 <- lm(price ~ sqft_living + waterfront + parks_nn1, data = kc_variables_sf)
summary(lm.fit2)
```

